import "../../styles/global.css"
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import '../../styles/cards.css'
import Nav from "../../components/Nav";
import Footer from "../../components/Footer";
import { GeistSans } from 'geist/font/sans';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Look King Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Nav/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
