import "../../styles/global.css"
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import '../../styles/cardsStyle/fc.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Look King Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
